/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.notforme

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class TipCalculatorTest {

    @Test
    fun testCalculatorReceiveBillAndTipPercent() {
        val testDataSet = listOf(
                Triple(100.0F, 10, 10.0F),
                Triple(11.25F, 15, 1.69F)
        )

        testDataSet.forEach {
            val testBill = it.first
            val testTipPercentage = it.second
            val tip = it.third

            val bill: Bill = TipCalculator().calculate(testBill, testTipPercentage)
            assertNotNull(bill)
            assertEquals(testBill, bill.total - bill.tip)
            assertEquals(testTipPercentage.toFloat() / 100, bill.tipRate)
            assertEquals(tip, bill.tip)
            assertEquals(testBill + tip, bill.total)
        }
    }
}
