/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.notforme
/**
 * 요구사항: 가격과 팁 비율을 입력 받아 팁을 계산하여 팁과 전체 가격을 표시
 * 제약조건:
 *  1) 팁은 반드시 퍼센트 단위(양의 정수), 예: 15%는 0.15가 아닌 15 => 완료
 *  2) 계산된 팁은 센트 단위로 반올림 => 완료
 * 추가 요구사항:
 *  1) 가격과 팁 비율 값으로 숫자만 입력 받기, 아니면 종료
 *  2) 잘못 입력된 값 => 재입력 요구
 *  3) 음수값 안 받기 => 완료
 *  4) 연산 부분을 함수 처리 => 완료
 *  5) GUI로 개선
 *  6) GUI에서 팁 비율을 슬라이드로 받음, 범위는 5-20
 */
class TipCalculator {
    fun calculate(bill: Float, tipPercentage: Int): Bill {
       validateArgs(bill, tipPercentage)

        val tipRate = tipPercentage.toFloat() / 100
        // Round up to 2 decimal
        val tip = Math.round(bill * tipRate * 100) / 100.0F
        val total = bill + tip
        return Bill(total, tip, tipRate)
    }

    private fun validateArgs(bill: Float, tipPercentage: Int) {
        if (bill < 1) {
            throw IllegalArgumentException("invalid bill amount")
        }

        if (!isValidTipPercentageRange(tipPercentage)) {
            throw IllegalArgumentException("invalid tip percentage")
        }
    }

    private fun isValidTipPercentageRange(tipPercentage: Int) = tipPercentage in 10..15

    fun runCalculator() {
        print("What is the bill? ")
        // Double Bang: https://kotlinlang.org/docs/reference/null-safety.html
        val billAmount = readLine()!!.toFloat()

        print("What is the tip percentage? ")
        val tipPercentage = readLine()!!.toInt()

        val bill = TipCalculator().calculate(billAmount, tipPercentage)

        println("The tip is ${bill.tip}")
        println("The total is ${bill.total}")
    }
}

/**
 *  pseudo-code
 *
 * 1. Prompt and Receive user input for billAmount and tipPercentage
 * 2. Calculate tip and total
 * 2-1. tip = billAmount * (tipPercentage/100)
 * 2-2. Round the tip to nearest cent
 * 2-3. total = billAmount + top
 * 3. Display result
 */
fun main(args: Array<String>) {
    println("Hello Kotlin")
    TipCalculator().runCalculator()
}
