/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.notforme

class TipCalculator {
    fun calculate(bill: Float, tipPercentage: Int): Bill {
       validateArgs(bill, tipPercentage)

        val tipRate = tipPercentage.toFloat() / 100
        // Round up to 2 decimal
        val tip = Math.round(bill * tipRate * 100) / 100.0F
        val total = bill + tip
        return Bill(total, tip, tipRate)
    }

    private fun validateArgs(bill: Float, tipPercentage: Int) {
        if (bill < 1) {
            throw IllegalArgumentException("invalid bill amount")
        }

        if (!isValidTipPercentageRange(tipPercentage)) {
            throw IllegalArgumentException("invalid tip percentage")
        }
    }

    private fun isValidTipPercentageRange(tipPercentage: Int) = tipPercentage in 10..15

    fun runCalculator() {
        print("What is the bill? ")
        // Double Bang: https://kotlinlang.org/docs/reference/null-safety.html
        val billAmount = readLine()!!.toFloat()

        print("What is the tip percentage? ")
        val tipPercentage = readLine()!!.toInt()

        val bill = TipCalculator().calculate(billAmount, tipPercentage)

        println("The tip is ${bill.tip}")
        println("The total is ${bill.total}")
    }
}

/**
 *  pseudo-code
 *
 * 1. Prompt and Receive user input for billAmount and tipPercentage
 * 2. Calculate tip and total
 * 2-1. tip = billAmount * (tipPercentage/100)
 * 2-2. Round the tip to nearest cent
 * 2-3. total = billAmount + top
 * 3. Display result
 */
fun main(args: Array<String>) {
    println("Hello Kotlin")
    TipCalculator().runCalculator()
}
