/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.notforme

class TipCalculator {
    fun calculate(bill: Float, tipPercentage: Int): Bill {

        val tipRate = tipPercentage.toFloat() / 100
        // Round up to 2 decimal
        val tip = Math.round(bill * tipRate * 100) / 100.0F
        val total = bill + tip
        return Bill(total, tip, tipRate)
    }
}

/**
 *  pseudo-code
 *
 * 1. Prompt and Receive user input for billAmount and tipPercentage
 * 2. Calculate tip and total
 * 2-1. tip = billAmount * (tipPercentage/100)
 * 2-2. Round the tip to nearest cent
 * 2-3. total = billAmount + top
 * 3. Display result
 */
fun main(args: Array<String>) {
  println("Hello Kotin") 
}

fun debug() {
     print("What is the bill? ")
    // Double Bang: https://kotlinlang.org/docs/reference/null-safety.html
    val billAmount = readLine()!!.toFloat()

    print("What is the tip percentage? ")
    val tipPercentage = readLine()!!.toInt()

    val bill = TipCalculator().calculate(billAmount, tipPercentage)

    println("The tip is ${bill.tip}")
    println("The total is ${bill.total}")
}